package com.auraface.auraface_app.core.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Login : Screen("login")
    object MainDashboard : Screen("main_dashboard")
    object AdminDashboard : Screen("admin_dashboard")
    object ManageStudents : Screen("manage_students")
    object ManageTeachers : Screen("manage_teachers")
    object ManageSubjects : Screen("manage_subjects")
    object TeacherDashboard : Screen("teacher_dashboard")
    object StudentDashboard : Screen("student_dashboard")
    object AdminStudents : Screen("admin_students")
    object AdminDefaulters : Screen("admin_defaulters")
    object Camera : Screen("camera")
    object StudentAttendance : Screen("student_attendance")
    object Attendance : Screen("attendance/{subjectId}") {
        fun createRoute(subjectId: String) =
            "attendance/$subjectId"
    }
    object AdminReports : Screen("admin_reports")
    object ManageTimetable : Screen("manage_timetable")
    object StudentProfile : Screen("student_profile")
    object StudentHistory : Screen("my_attendance")
    object StudentLeave : Screen("issue_letter")
    object TeacherSectionLeave : Screen("teacher_section_leave")
    object TeacherHodLeave : Screen("teacher_hod_leave")
    object TeacherProfile : Screen("teacher_profile")
    object Settings : Screen("settings")
    object RealTimeMonitoring : Screen("real_time_monitoring")
    object SmartNotices : Screen("smart_notices")
    object SmartInsights : Screen("smart_insights")
    object SmartLibrary : Screen("smart_library")
    object AuraChat : Screen("aura_chat")
    object SendNotice : Screen("send_notice")
    object ExamSchedule : Screen("exam_schedule")
    object ExamResults : Screen("exam_results")
    object CGPACalculator : Screen("cgpa_calculator")
    object UploadMarks : Screen("upload_marks")
    object MyClass : Screen("my_class")
    object QuizGame : Screen("quiz_game")
    object AddQuizQuestion : Screen("add_quiz_question")
    object ChatMain : Screen("chat_main")
    object RewardsStore : Screen("rewards_store")
    object AuraFocus : Screen("aura_focus")
    object AuraPulse : Screen("aura_pulse")
    object CampusPulse : Screen("campus_pulse")
    object AuraQuests : Screen("aura_quests")
    object AuraBites : Screen("aura_bites")
    object AuraSpaces : Screen("aura_spaces")
    object AuraFound : Screen("aura_found")
    object CampusMovies : Screen("campus_movies")
    object CampusSports : Screen("campus_sports")
}
